sudo: required
dist: trusty
language: python
python:
  - "2.7"
branches:
  only:
    - master
services:
  - redis-server
install:
  - make reqs
before_script:
  - sudo make conf
script:
  - make tests
